[project]
name = "PassMaster"
version = "0.1.0"
description = "Secure password manager cli"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click==8.3.0",
    "tabulate==0.9.0",
]